name: 'Tests: node.js < 10'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '>=8.3 < 10'
      type: minors
      command: npm run tests-only

  node:
    name: 'node >= 8.3 && < 10'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
